services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      HOST: "0.0.0.0"
      REDIS_SERVER: "db"
      REDIS_PORT: 6379
    ports:
      - "8081:8081"
    networks:
      - taiwan_arrivals_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - taiwan_arrivals_network

networks:
  taiwan_arrivals_network:
    driver: bridge